{% set name = "nessai" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nessai-{{ version }}.tar.gz
  sha256: 65ba79f52721ec2e9802c3d2fdfdebdfbc6b2fb4fd81d2a69a8b0351bebfe8c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - glasflow
    - h5py
    - matplotlib-base >=2.0
    - numpy >=1.9
    - pandas
    - python >={{ python_min }}
    - scipy >=0.16
    - seaborn
    - pytorch >=1.11.0
    - tqdm
    - importlib-metadata

test:
  requires:
    - pip
    - corner
    - pytest >=0.6.0
    - pytest-cov
    - pytest-integration
    - pytest-rerunfailures
    - pytest-timeout
    - python {{ python_min }}
  imports:
    - nessai
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pip check
    - python -m pytest tests/ -vv -k "not (integration_test or slow_integration_test)"

about:
  home: https://github.com/mj-will/nessai
  dev_url: https://github.com/mj-will/nessai
  doc_url: https://nessai.readthedocs.io
  summary: 'nessai: Nested Sampling with Artificial Intelligence'
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  description: |
    nessai is a nested sampling algorithm for Bayesian Inference that
    incorporates normalisings flows. It is designed for applications where the
    Bayesian likelihood is computationally expensive.

extra:
  recipe-maintainers:
    - johnveitch
    - mj-will
